### ISSUE TITLE
Font style is overriden by font-variant or font-weight

### ISSUE THREAD

**Issue by carmelc** [jedmao/parse-css-font#12]
Given a font _'italic normal normal 18px/1.4em "open sans",sans-serif;'_ the following section - https://github.com/jedmao/parse-css-font/blob/master/src/index.ts#L53-L59 will recognize the second and third tokens as "normal" and will set 'style', 'variant', 'weight' and 'stretch' to normal, even though the style was already set as italic (it is being overriden).
I suppose that you should keep track of which tokens you already set and filter them out, so you are not overriding them by a later 'normal' token.
What is the logic around this check and setting of these font properties?

**Comment by jedmao** [comment]
1. This appears to be a bug.
1. I agree that I should keep track of which tokes are already set and filter them out.
1. The logic around this check is the following formal syntax: [`[ <'font-style'> || <font-variant-css21> || <'font-weight'> || <'font-stretch'> ]?`](https://developer.mozilla.org/en-US/docs/Web/CSS/font#Formal_syntax). The `||` operator combined with `?` instead of `*` threw me off, misleading me into thinking that only one could be supplied, without repetition.

I'm still quite confused, in fact, because the following CSS doesn't validate:

```css
p {
  font: italic small-caps bold expanded 18px/1.4em "open sans", sans-serif;
}
```

It seems to have a problem with the `font-stretch: expanded` part.

Do you have a more human way to interpret how this portion of the formal syntax should operate?

**Comment by carmelc** [comment]
What do you mean by a problem with expanded? this is a valid font,
The part which is confusing in MDN is that each part is optional, but the order is important.
I am thinking that maybe you can remove this part altogether and just default these attributes to "normal", 
WDYT?

**Comment by jedmao** [comment]
`expanded` is a valid `font-stretch`, but it doesn't validate via [The W3C CSS Validation Service](http://jigsaw.w3.org/css-validator/#validate_by_input).

I don't want to guess anything here, so I'm afraid I'm still not 100% comfortable with a solution.

Anyone out there know more about how this works or why my example above is failing CSS validation?

**Comment by carmelc** [comment]
I guess that it is simply because they define font without the option to define a font-stretch,
See https://www.w3schools.com/cssref/pr_font_font.asp, w3schools defines the structure as:

> The font property is a shorthand property for:
>  - font-style
>  - font-variant
>  - font-weight
>  - font-size/line-height
>  - font-family

I am usually considering MDN as a more reliable source, either case, the logic in question should be removed.
Let me know if you are OK with that and I will remove the check, the props are already defaulted to 'normal'.

**Comment by carmelc** [comment]
I think that it is the other way around, that MDN is correct.
I tested in a browser and font-stretch is supported, so it seems that W3schools are missing this props and the error is on their side.

**Comment by jedmao** [comment]
Not just W3schools but the W3C validation service is missing it as well. That's what's so disconcerting!

**Comment by jedmao** [comment]
https://codepen.io/jedmao/pen/omxqbv
- Chrome and Firefox both parse the shorthand and convert the `font-stretch` into `125%`.
- Microsoft Edge does not parse the font shorthand and doesn't even set the font size or anything else as a result of the "error" unless I remove `expanded`.

I think it's safe to say that this package should support the `font-stretch`.

**Comment by carmelc** [comment]
According to https://drafts.csswg.org/css-fonts-3/#propdef-font there is a forth property font-strech,
according to https://www.w3.org/TR/CSS2/fonts.html#font-shorthand there isn't, but there is a disclaimer at the bottom that this is not the most up to date, and ["Cascading Style Sheets (CSS) — The Official Definition"](https://www.w3.org/TR/CSS/#css) should be used, So I am guessing that the package should support it.
So do we agree that the logic mentioned at the begining of the thread should be removed?

**Comment by jedmao** [comment]
I'm not sure if removed is the right solution. I think it needs to be changed. First step is to submit a PR with breaking tests.
