### ISSUE TITLE
ES module being exported instead of function

### ISSUE THREAD

**Issue by dy** [jedmao/parse-css-font#6]
Readme example does not work:

```js
var parseCSSFont = require('parse-css-font');
```

`parseCSSFont` is `{default: parse, __esModule: true}` object.
Is that possible to rebundle it to be a real function? Appreciate @jedmao!

**Comment by jedmao** [comment]
Can you just use `.default` for now?

**Comment by jednano** [comment]
@dy I published this as v3.0.3. I also noticed you have a number of commits on your own fork. Please submit any remaining issues to this issue tracker. Thanks!
