### ISSUE TITLE
Parse random font variant

### ISSUE THREAD

**Issue by dy** [jedmao/parse-css-font#9]
```js
var parse = require('parse-css-font').default
console.log(parse('foo 1rem serif'))
// { variant: 'foo', ... }
```

I wonder why is that allowed for `variant` to be any value? According to the spec that can be only `small-caps` or `normal` https://developer.mozilla.org/en-US/docs/Web/CSS/font#font-variant-css21. Is that done so for the future?

**Comment by jedmao** [comment]
It's actually [a lot more complicated than that](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant).
